version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
  db:
    image: mysql:8.1
    container_name: db
    env_file:
      - mysql.env
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - mysql.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/$MYSQL_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'

  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:latest
    restart: on-failure
    ports:
      - 3000:80
    depends_on:
      - back
    
