version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "~/certificateFiles/www-001.crt:/ssl/www-001.crt"
      - "~/certificateFiles/privatekey.key:/ssl/privatekey.key"
    networks:
      - lc-net

  db:
    image: mysql:8.1
    container_name: db
    env_file:
      - mysql.env
    volumes:
      - "../data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - db-net

  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:stable
    restart: on-failure
    depends_on:
      - db
    env_file:
      - backend.env
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      NODEX: nodex
    networks:
      - lc-net
      - db-net
      - ex-net
      
  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:stable
    restart: on-failure
    depends_on:
      - back
    volumes:
      - "./config/web-server.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - lc-net
  
  nodex:
    container_name: nodex
    image: ghcr.io/sit-lightcode/nodex:stable
    restart: on-failure
    networks:
      - ex-net
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  lc-net:
    driver: bridge
  db-net:
    driver: bridge
  ex-net:
    driver: bridge
