version: '3.1'
services:
  mysql:
    image: mysql:8.1
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
      - "./script:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}