version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
  db:
    image: mysql:8.1
    container_name: db
    env_file:
      - mysql.env
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
      - "./script:/docker-entrypoint-initdb.d"
  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:latest
    restart: on-failure
    ports:
      - 3000:80
    depends_on:
      - back
