version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "~/certificateFiles/www-001.crt:/ssl/www-001.crt"
      - "~/certificateFiles/privatekey.key:/ssl/privatekey.key"
  db:
    image: mysql:8.1
    container_name: db
    env_file:
      - mysql.env
    ports:
      - 3306:3306
    volumes:
      - "../data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:stable
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - backend.env
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306

  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:stable
    restart: on-failure
    ports:
      - 3000:80
    depends_on:
      - back
    volumes:
      - "./config/web-server.conf:/etc/nginx/conf.d/default.conf"
    
