version: '3.1'
services:
  db:
    image: mysql:8.1
    container_name: db
    ports:
      - 3308:3306
    volumes:
      - "./data:/var/lib/mysql"
      - "./script:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:latest
    restart: on-failure
    ports:
      - 80:3000
    depends_on:
      - back
