version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy-dev.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - lc-net
      
  db:
    image: mysql:8.1
    container_name: db
    restart: always
    env_file:
      - mysql.env
    ports:
      - 3306:3306
    volumes:
      - "../data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - db-net
  nodex:
    container_name: nodex
    image: ghcr.io/sit-lightcode/nodex:dev
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - ex-net

  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:dev
    restart: on-failure
    volumes:
      - "../log:/logs"
    ports:
      - 8080:8080
    depends_on:
      - db
      - nodex
    env_file:
      - backend.env
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      NODEX: nodex
    networks:
      - lc-net
      - db-net
      - ex-net
  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:dev
    restart: on-failure
    ports:
      - 3000:80
    depends_on:
      - back
    volumes:
      - "./config/web-server.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - lc-net
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: always
    ports:
      - "9000:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    restart: always
    ports:
      - '9100:9100'
networks:
  lc-net:
    driver: bridge
  db-net:
    driver: bridge
  ex-net:
    driver: bridge
