version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
  db:
    image: ghcr.io/sit-lightcode/database:latest
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - backend.env
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306

  front:
    container_name: front
    image: ghcr.io/sit-lightcode/front-end:latest
    restart: on-failure
    ports:
      - 3000:80
    depends_on:
      - back
    volumes:
      - "./config/web-server.conf:/etc/nginx/conf.d/default.conf"
    
