version: '3.1'
services:
  # db:
  #   image: mysql:8.1
  #   ports:
  #     - 3308:3306
  #   volumes:
  #     - "./data:/var/lib/mysql"
  #     - "./script:/docker-entrypoint-initdb.d"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWD }}
  back:
    container_name: back
    image: ghcr.io/sit-lightcode/back-end:test
    restart: on-failure
    depends_on:
      - db
