SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `lightcode` DEFAULT CHARACTER SET utf8mb3 ;
USE `lightcode` ;

CREATE TABLE IF NOT EXISTS `lightcode`.`tag` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `topic_UNIQUE` (`topic` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS `lightcode`.`lesson` (
  `name` VARCHAR(100) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `tag_id` INT NOT NULL,
  `lesson_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`lesson_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
    CONSTRAINT `fk_myanswer_has_question_myanswer1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `lightcode`.`tag` (`tag_id`))
    
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER IF NOT EXISTS  'dev'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON * . * TO 'dev'@'%';
FLUSH PRIVILEGES;