name: 'Build push snapshot image'
on:
  workflow_call:

jobs:
  build-back-image:
    # needs: install-back-dependencies
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.step1.meta.outputs.tags }}
      labels: ${{ steps.step1.meta.outputs.labels }}
      actorUsername: ${{ github.actor }}
      pat: ${{ secrets.GHCR_PAT }}

    steps:
    - uses: actions/checkout@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ needs.build-back-image.outputs.actorUsername }}
        password: ${{ needs.build-back-image.outputs.pat }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/SIT-LightCode/front-end
        tags: |
          type=sha
          latest

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ needs.build-back-image.outputs.tags }}
        labels: ${{ needs.build-back-image.outputs.labels }}