name: 'deploy on production'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: SSH into the Server and Run docker-compose
      env:
        PROD_PWD: ${{ secrets.PROD_PWD }}
        PROD_ADMIN: ${{ secrets.PROD_ADMIN }}
        PROD_HOSTNAME: ${{ secrets.PROD_HOSTNAME }}
        TUS_GH_USER: ${{ secrets.TUS_GH_USER }}
        GHCR_PAT: ${{ secrets.GHCR_PAT }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWD }}
        MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      run: |
        sshpass -p $PROD_PWD ssh -tt -o StrictHostKeyChecking=no $PROD_ADMIN@$PROD_HOSTNAME << EOF
          cd ~/LC-Deployment
          envsubst < mysql.env.tmpl > mysql.env
          envsubst < backend.env.tmpl > backend.env
          docker login ghcr.io -u $TUS_GH_USER -p $GHCR_PAT
          git pull
          docker-compose pull
          docker-compose up -d
          exit
        EOF
    - name: run hostname
      run: hostname

