name: 'deploy'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: SSH into the Server and Run docker-compose
      run: |
        sshpass -p lc12345 ssh -tt -o StrictHostKeyChecking=no sysadmin@cp23us1.sit.kmutt.ac.th << EOF
          cd ~/LC-Deployment
          docker-compose up -d
          exit
        EOF
    - name: run hostname
      run: hostname
    #     docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    # - name: Login to GHCR
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
