name: 'deploy'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.PROD_HOSTNAME }}
        user: ${{ secrets.PROD_ADMIN }}
        pass: ${{ secrets.PROD_PWD }}
        port: ${{ secrets.SSH_PORT }}
        connect_timeout: 10s
        first_ssh: |
          docker-compose pull
          docker-compose --build -d
    - name: Run application
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_HOSTNAME }}
        username: ${{ secrets.PROD_ADMIN }}
        key: ${{ secrets.RUNNER_KEY }}
        script: |
          docker-compose pull
          docker-compose --build -d
    - name: run hostname
      run: hostname
    #     docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    # - name: Login to GHCR
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
