name: 'deploy'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOSTNAME }}
        username: ${{ secrets.PROD_ADMIN }}
        key: ${{ secrets.RUNNER_KEY }}
        script: |
          docker-compose pull
          docker-compose --build -d
    - name: run hostname
      run: hostname
    #     docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    # - name: Login to GHCR
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
