name: 'deploy'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands
      run: | 
        sshpass -p ${{ secrets.PROD_PWD }} ssh ${{secrets.PROD_ADMIN}}@${{secrets.PROD_HOSTNAME}}
    - name: run hostname
      run: hostname
    #     docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    # - name: Login to GHCR
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    