name: 'deploy on production'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: SSH into the Server and Run docker-compose
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWD }}
        MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      run: |
        bash script.sh
    - name: run hostname
      run: hostname

