name: "deploy nodex"
on:
  workflow_dispatch:
    inputs:
      restart:
        description: "down service before up again"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: SSH into the Server and Run docker-compose
        env:
          NODEX_PWD: ${{ secrets.NODEX_PWD }}
          NODEX_ADMIN: ${{ secrets.NODEX_ADMIN }}
          NODEX_HOSTNAME: ${{ secrets.NODEX_HOSTNAME }}
          NODEX_PRIVATE_KEY: ${{ secrets.NODEX_PRIVATE_KEY }}
          TUS_GH_USER: ${{ secrets.TUS_GH_USER }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          RESTART: ${{inputs.restart}}

        run: |
          echo "yes" | sshpass -p $NODEX_PWD ssh -tt -o StrictHostKeyChecking=no $NODEX_ADMIN@$NODEX_HOSTNAME << EOF
            docker login ghcr.io -u $TUS_GH_USER -p $GHCR_PAT
            eval "$(ssh-agent -s)"
            ssh-add $NODEX_PRIVATE_KEY
            if [[ -f "LC-Deployment" ]]
            then
              echo "LC-Deployment exists."
            else
              echo "yes" | git clone git@github.com:SIT-LightCode/LC-Deployment.git
            fi          

            cd ~/LC-Deployment

            if [[ $RESTART = "yes" ]]
            then
              docker-compose down
            fi
            
            git pull
            docker-compose -f docker-compose-nodex.yml pull
            docker-compose -f docker-compose-nodex.yml up -d
            echo y | docker system prune -a
            exit
          EOF