name: "deploy nodex"
on:
  workflow_dispatch:
    inputs:
      restart:
        description: "down service before up again"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: SSH into the Server and Run docker-compose
        env:
          DEV_PWD: ${{ secrets.NODEX_PWD }}
          DEV_ADMIN: ${{ secrets.NODEX_ADMIN }}
          DEV_HOSTNAME: ${{ secrets.NODEX_HOSTNAME }}
          TUS_GH_USER: ${{ secrets.TUS_GH_USER }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          RESTART: ${{inputs.restart}}

        run: |
            docker login ghcr.io -u $TUS_GH_USER -p $GHCR_PAT
            if [[ -f "LC-Deployment" ]]
            then
              echo "LC-Deployment exists."
            else
              echo "yes" | git clone git@github.com:SIT-LightCode/LC-Deployment.git
            fi          

            cd ~/LC-Deployment

            if [[ $RESTART = "yes" ]]
            then
              docker-compose down
            fi
            
            git pull
            echo y | docker system prune -a
