name: 'deploy'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands
      run: echo ${{ secrets.PROD_PWD }} | ssh sysadmin@cp23us1.sit.kmutt.ac.th
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    