name: 'deploy on production'
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: SSH into the Server and Run docker-compose
      env:
        PROD_PWD: ${{ secrets.PROD_PWD }}
        PROD_ADMIN: ${{ secrets.PROD_ADMIN }}
        PROD_HOSTNAME: ${{ secrets.PROD_HOSTNAME }}
        TUS_GH_USER: ${{ secrets.TUS_GH_USER }}
        GHCR_PAT: ${{ secrets.GHCR_PAT }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWD }}
        MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      run: |
        bash script.sh
    - name: run hostname
      run: hostname

