name: Check Service Status

# on:
#   schedule:
#     - cron: "*/5 * * * *"

on:
  push:
    branches:
      - main # Change 'main' to the branch you want to trigger the workflow on

jobs:
  check-api-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check the API and set the status as env var
        id: api-check
        uses: actions/github-script@v5
        with:
          script: |
            const axios = require('axios')
            const response = await axios.get('http://lightcodedev.sit.kmutt.ac.th:8080/api/v1/details')
            const status = response.data.status          
            return status

      - name: Setup env
        run: echo "STATUS=${{ steps.api-check.outputs.result }}" >> $GITHUB_ENV

      - name: Determine message and mention
        id: determine-msg
        run: |
          if [[ "${STATUS}" != "Alive" ]]; then
            # Add your desired message 
            echo "MENTION=<@&1157965476970909748>" >> $GITHUB_ENV
            echo "MESSAGE=ALERT! Status is '${STATUS}'." >> $GITHUB_ENV
          fi

      - steps:
          - name: Send Discord message
            if: env.MESSAGE
            run: |
              curl -X POST -H "Content-Type: application/json" \
                -d '{"content": "'"${MESSAGE}"'"}' \
                "https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}"
