name: Check Service Status

# on:
#   schedule:
#     - cron: "*/5 * * * *"

on:
  push:
    branches:
      - main # Change 'main' to the branch you want to trigger the workflow on

jobs:
  check-api-status:
    runs-on: self-hosted
    steps:
      - name: Check the API and set status as env var
        id: api-check
        run: |
          STATUS=$(curl -s 'http://lightcodedev.sit.kmutt.ac.th:8080/api/v1/details' | jq -r .status)
          echo "STATUS=${STATUS}" >> $GITHUB_ENV

      - name: Determine message and mention
        id: determine-msg
        run: |
          if [[ "${{ env.STATUS }}" != "Alive2" ]]; then
            echo "MESSAGE=<@&1157965476970909748> ALERT! Status is '${{ env.STATUS }}'." >> $GITHUB_ENV
          fi

      - name: Send Discord message
        if: env.MESSAGE
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "'"${{ env.MESSAGE }}"'"}' \
            "https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/}${{ secrets.WEBHOOK_TOKEN }}"
