name: Check Service Status

# on:
#   schedule:
#     - cron: "*/5 * * * *"

on:
  push:
    branches:
      - main # Change 'main' to the branch you want to trigger the workflow on

jobs:
  check-api-status:
    runs-on: self-hosted
    steps:
      - name: Check the API and set the status as env var
        id: api-check
        uses: actions/github-script@v5
        with:
          script: |
            const response = await fetch('http://lightcodedev.sit.kmutt.ac.th:8080/api/v1/details');
            const data = await response.json();
            const status = data.status;            
            return status;

      - name: Setup env
        run: echo "STATUS=${{ steps.api-check.outputs.result }}" >> $GITHUB_ENV

      - name: Determine message and mention
        id: determine-msg
        run: |
          if [[ "${{ env.STATUS }}" != "Alive2" ]]; then
            echo "MESSAGE=<@&1157965476970909748> ALERT! Status is '${{ env.STATUS }}'." >> $GITHUB_ENV
          fi

      - name: Send Discord message
        if: env.MESSAGE
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "'"${{ env.MESSAGE }}"'"}' \
            "<https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/}${{ secrets.WEBHOOK_TOKEN }}"
